<?php

namespace Container8UZoXME;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_ZkQamH8Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.ZkQamH8' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.ZkQamH8'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'repository' => ['privates', 'App\\Repository\\ContentRepository', 'getContentRepositoryService', false],
        ], [
            'repository' => 'App\\Repository\\ContentRepository',
        ]);
    }
}
