<?php

namespace Container8UZoXME;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPriceClassRepositoryService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Repository\PriceClassRepository' shared autowired service.
     *
     * @return \App\Repository\PriceClassRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Repository'.\DIRECTORY_SEPARATOR.'PriceClassRepository.php';

        return $container->privates['App\\Repository\\PriceClassRepository'] = new \App\Repository\PriceClassRepository(($container->services['doctrine'] ?? $container->getDoctrineService()));
    }
}
