<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class PriceService extends \App\Entity\PriceService implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array<string, null> properties to be lazy loaded, indexed by property name
     */
    public static $lazyPropertiesNames = array (
);

    /**
     * @var array<string, mixed> default values of properties to be lazy loaded, with keys being the property names
     *
     * @see \Doctrine\Common\Proxy\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array (
);



    public function __construct(?\Closure $initializer = null, ?\Closure $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'App\\Entity\\PriceService' . "\0" . 'id', '' . "\0" . 'App\\Entity\\PriceService' . "\0" . 'name', '' . "\0" . 'App\\Entity\\PriceService' . "\0" . 'hours', '' . "\0" . 'App\\Entity\\PriceService' . "\0" . 'contents', '' . "\0" . 'App\\Entity\\PriceService' . "\0" . 'priceCategory', '' . "\0" . 'App\\Entity\\PriceService' . "\0" . 'beforeAfterImages', '' . "\0" . 'App\\Entity\\PriceService' . "\0" . 'published', '' . "\0" . 'App\\Entity\\PriceService' . "\0" . 'priceOfHour', '' . "\0" . 'App\\Entity\\PriceService' . "\0" . 'increase', '' . "\0" . 'App\\Entity\\PriceService' . "\0" . 'path', '' . "\0" . 'App\\Entity\\PriceService' . "\0" . 'nameInPriceList', '' . "\0" . 'App\\Entity\\PriceService' . "\0" . 'slug', '' . "\0" . 'App\\Entity\\PriceService' . "\0" . 'pagetitle', '' . "\0" . 'App\\Entity\\PriceService' . "\0" . 'excludedSalons'];
        }

        return ['__isInitialized__', '' . "\0" . 'App\\Entity\\PriceService' . "\0" . 'id', '' . "\0" . 'App\\Entity\\PriceService' . "\0" . 'name', '' . "\0" . 'App\\Entity\\PriceService' . "\0" . 'hours', '' . "\0" . 'App\\Entity\\PriceService' . "\0" . 'contents', '' . "\0" . 'App\\Entity\\PriceService' . "\0" . 'priceCategory', '' . "\0" . 'App\\Entity\\PriceService' . "\0" . 'beforeAfterImages', '' . "\0" . 'App\\Entity\\PriceService' . "\0" . 'published', '' . "\0" . 'App\\Entity\\PriceService' . "\0" . 'priceOfHour', '' . "\0" . 'App\\Entity\\PriceService' . "\0" . 'increase', '' . "\0" . 'App\\Entity\\PriceService' . "\0" . 'path', '' . "\0" . 'App\\Entity\\PriceService' . "\0" . 'nameInPriceList', '' . "\0" . 'App\\Entity\\PriceService' . "\0" . 'slug', '' . "\0" . 'App\\Entity\\PriceService' . "\0" . 'pagetitle', '' . "\0" . 'App\\Entity\\PriceService' . "\0" . 'excludedSalons'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (PriceService $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy::$lazyPropertiesDefaults as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @deprecated no longer in use - generated code now relies on internal components rather than generated public API
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getPriceOfHour(): int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPriceOfHour', []);

        return parent::getPriceOfHour();
    }

    /**
     * {@inheritDoc}
     */
    public function getIncrease(): int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIncrease', []);

        return parent::getIncrease();
    }

    /**
     * {@inheritDoc}
     */
    public function getId(): ?int
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getName(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getName', []);

        return parent::getName();
    }

    /**
     * {@inheritDoc}
     */
    public function setName(?string $name): \App\Entity\PriceService
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setName', [$name]);

        return parent::setName($name);
    }

    /**
     * {@inheritDoc}
     */
    public function getHours(): ?float
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getHours', []);

        return parent::getHours();
    }

    /**
     * {@inheritDoc}
     */
    public function setHours(float $hours): \App\Entity\PriceService
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setHours', [$hours]);

        return parent::setHours($hours);
    }

    /**
     * {@inheritDoc}
     */
    public function getContents(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getContents', []);

        return parent::getContents();
    }

    /**
     * {@inheritDoc}
     */
    public function addContent(\App\Entity\Service $content): \App\Entity\PriceService
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addContent', [$content]);

        return parent::addContent($content);
    }

    /**
     * {@inheritDoc}
     */
    public function removeContent(\App\Entity\Service $content): \App\Entity\PriceService
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeContent', [$content]);

        return parent::removeContent($content);
    }

    /**
     * {@inheritDoc}
     */
    public function getPriceCategory(): ?\App\Entity\PriceCategory
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPriceCategory', []);

        return parent::getPriceCategory();
    }

    /**
     * {@inheritDoc}
     */
    public function getBrandById(int $id, \App\Repository\PriceBrandRepository $priceBrandRepository)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBrandById', [$id, $priceBrandRepository]);

        return parent::getBrandById($id, $priceBrandRepository);
    }

    /**
     * {@inheritDoc}
     */
    public function setPriceCategory(?\App\Entity\PriceCategory $priceCategory): \App\Entity\PriceService
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPriceCategory', [$priceCategory]);

        return parent::setPriceCategory($priceCategory);
    }

    /**
     * {@inheritDoc}
     */
    public function setPriceByContent(\App\Entity\Content $content, \App\Repository\PriceModelRepository $priceModelRepository)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPriceByContent', [$content, $priceModelRepository]);

        return parent::setPriceByContent($content, $priceModelRepository);
    }

    /**
     * {@inheritDoc}
     */
    public function setPathByContent(\App\Entity\Content $content, \App\Repository\RootServiceRepository $rootServiceRepository, \App\Repository\ContentRepository $contentRepository, \App\Repository\PriceBrandRepository $priceBrandRepository, \App\Repository\PriceModelRepository $priceModelRepository): \App\Entity\PriceService
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPathByContent', [$content, $rootServiceRepository, $contentRepository, $priceBrandRepository, $priceModelRepository]);

        return parent::setPathByContent($content, $rootServiceRepository, $contentRepository, $priceBrandRepository, $priceModelRepository);
    }

    /**
     * {@inheritDoc}
     */
    public function setPathForRootService(\App\Repository\RootServiceRepository $rootServiceRepository): void
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPathForRootService', [$rootServiceRepository]);

        parent::setPathForRootService($rootServiceRepository);
    }

    /**
     * {@inheritDoc}
     */
    public function getPrice()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPrice', []);

        return parent::getPrice();
    }

    /**
     * {@inheritDoc}
     */
    public function getPath()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPath', []);

        return parent::getPath();
    }

    /**
     * {@inheritDoc}
     */
    public function __toString()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, '__toString', []);

        return parent::__toString();
    }

    /**
     * {@inheritDoc}
     */
    public function getBeforeAfterImages(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBeforeAfterImages', []);

        return parent::getBeforeAfterImages();
    }

    /**
     * {@inheritDoc}
     */
    public function addBeforeAfterImage(\App\Entity\BeforeAfter $beforeAfterImage): \App\Entity\PriceService
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addBeforeAfterImage', [$beforeAfterImage]);

        return parent::addBeforeAfterImage($beforeAfterImage);
    }

    /**
     * {@inheritDoc}
     */
    public function removeBeforeAfterImage(\App\Entity\BeforeAfter $beforeAfterImage): \App\Entity\PriceService
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeBeforeAfterImage', [$beforeAfterImage]);

        return parent::removeBeforeAfterImage($beforeAfterImage);
    }

    /**
     * {@inheritDoc}
     */
    public function getPublished(): ?bool
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPublished', []);

        return parent::getPublished();
    }

    /**
     * {@inheritDoc}
     */
    public function setPublished(bool $published): \App\Entity\PriceService
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPublished', [$published]);

        return parent::setPublished($published);
    }

    /**
     * {@inheritDoc}
     */
    public function getSlug(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSlug', []);

        return parent::getSlug();
    }

    /**
     * {@inheritDoc}
     */
    public function setSlug(?string $slug): \App\Entity\PriceService
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSlug', [$slug]);

        return parent::setSlug($slug);
    }

    /**
     * {@inheritDoc}
     */
    public function getExcludedSalons(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getExcludedSalons', []);

        return parent::getExcludedSalons();
    }

    /**
     * {@inheritDoc}
     */
    public function addExcludedSalon(\App\Entity\Salon $excludedSalon): \App\Entity\PriceService
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addExcludedSalon', [$excludedSalon]);

        return parent::addExcludedSalon($excludedSalon);
    }

    /**
     * {@inheritDoc}
     */
    public function removeExcludedSalon(\App\Entity\Salon $excludedSalon): \App\Entity\PriceService
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeExcludedSalon', [$excludedSalon]);

        return parent::removeExcludedSalon($excludedSalon);
    }

    /**
     * {@inheritDoc}
     */
    public function getNameInPriceList()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNameInPriceList', []);

        return parent::getNameInPriceList();
    }

    /**
     * {@inheritDoc}
     */
    public function getPagetitle(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPagetitle', []);

        return parent::getPagetitle();
    }

    /**
     * {@inheritDoc}
     */
    public function setPagetitle(?string $pagetitle): \App\Entity\PriceService
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPagetitle', [$pagetitle]);

        return parent::setPagetitle($pagetitle);
    }

}
