<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerOtsjnWH\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerOtsjnWH/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerOtsjnWH.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerOtsjnWH\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerOtsjnWH\App_KernelDevDebugContainer([
    'container.build_hash' => 'OtsjnWH',
    'container.build_id' => '61d954d1',
    'container.build_time' => 1626172750,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerOtsjnWH');
