<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    '_preview_error' => [['code', '_format'], ['_controller' => 'error_controller::preview', '_format' => 'html'], ['code' => '\\d+'], [['variable', '.', '[^/]++', '_format', true], ['variable', '/', '\\d+', 'code', true], ['text', '/_error']], [], []],
    '_wdt' => [['token'], ['_controller' => 'web_profiler.controller.profiler::toolbarAction'], [], [['variable', '/', '[^/]++', 'token', true], ['text', '/_wdt']], [], []],
    '_profiler_home' => [[], ['_controller' => 'web_profiler.controller.profiler::homeAction'], [], [['text', '/_profiler/']], [], []],
    '_profiler_search' => [[], ['_controller' => 'web_profiler.controller.profiler::searchAction'], [], [['text', '/_profiler/search']], [], []],
    '_profiler_search_bar' => [[], ['_controller' => 'web_profiler.controller.profiler::searchBarAction'], [], [['text', '/_profiler/search_bar']], [], []],
    '_profiler_phpinfo' => [[], ['_controller' => 'web_profiler.controller.profiler::phpinfoAction'], [], [['text', '/_profiler/phpinfo']], [], []],
    '_profiler_search_results' => [['token'], ['_controller' => 'web_profiler.controller.profiler::searchResultsAction'], [], [['text', '/search/results'], ['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], []],
    '_profiler_open_file' => [[], ['_controller' => 'web_profiler.controller.profiler::openAction'], [], [['text', '/_profiler/open']], [], []],
    '_profiler' => [['token'], ['_controller' => 'web_profiler.controller.profiler::panelAction'], [], [['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], []],
    '_profiler_router' => [['token'], ['_controller' => 'web_profiler.controller.router::panelAction'], [], [['text', '/router'], ['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], []],
    '_profiler_exception' => [['token'], ['_controller' => 'web_profiler.controller.exception_panel::body'], [], [['text', '/exception'], ['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], []],
    '_profiler_exception_css' => [['token'], ['_controller' => 'web_profiler.controller.exception_panel::stylesheet'], [], [['text', '/exception.css'], ['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], []],
    'admin' => [[], ['_controller' => 'App\\Controller\\Admin\\AdminController::index'], [], [['text', '/admin']], [], []],
    'contact' => [[], ['_controller' => 'App\\Controller\\ContactController::index'], [], [['text', '/kontaktyi/']], [], []],
    'home' => [[], ['_controller' => 'App\\Controller\\HomeController::index'], [], [['text', '/']], [], []],
    'contact_form' => [[], ['_controller' => 'App\\Controller\\MailerController::contact_form'], [], [['text', '/contact_form']], [], []],
    'vakancy_form' => [[], ['_controller' => 'App\\Controller\\MailerController::vakancy_form'], [], [['text', '/vakancy_form']], [], []],
    'callback_form' => [[], ['_controller' => 'App\\Controller\\MailerController::callback_form'], [], [['text', '/callback_form']], [], []],
    'offers' => [[], ['_controller' => 'App\\Controller\\OfferController::index'], [], [['text', '/offers']], [], []],
    'dinamic_offers' => [['token'], ['_controller' => 'App\\Controller\\OfferController::offer_item'], [], [['variable', '/', '[^/]++', 'token', true], ['text', '/offer']], [], []],
    'vakancy' => [['vakancy'], ['_controller' => 'App\\Controller\\PageController::vakancy'], ['token' => '\\/.+\\/'], [['variable', '/', '[^/]++', 'vakancy', true], ['text', '/vakancies']], [], []],
    'dynamic_pages' => [['token'], ['_controller' => 'App\\Controller\\PageController::index'], ['token' => '.+\\/'], [['variable', '/', '.+\\/', 'token', true]], [], []],
    'app_login' => [[], ['_controller' => 'App\\Controller\\SecurityController::login'], [], [['text', '/login']], [], []],
    'app_logout' => [[], ['_controller' => 'App\\Controller\\SecurityController::logout'], [], [['text', '/logout']], [], []],
    'sitemap' => [[], ['_controller' => 'App\\Controller\\SitemapController::index'], [], [['text', '/sitemap.xml']], [], []],
    'sitemap_part' => [['token'], ['_controller' => 'App\\Controller\\SitemapController::sitemap_part'], [], [['text', '.xml'], ['variable', '_', '[^/\\.]++', 'token', true], ['text', '/sitemap']], [], []],
];
